# Generated by Django 4.1.1 on 2022-09-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Epm',
        ),
    ]
