# Generated by Django 4.1.1 on 2022-09-23 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_epm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('us', models.BooleanField()),
            ],
        ),
    ]
