# Generated by Django 4.1.1 on 2022-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epm',
            name='us',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
