# Generated by Django 4.1.1 on 2022-09-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epm', '0002_epm_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epm',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='epm',
            name='sender',
        ),
    ]
